# Generated by Django 4.2.3 on 2023-08-03 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_feeding"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeding",
            name="plant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.plant",
            ),
            preserve_default=False,
        ),
    ]
